import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import prisma from "@/lib/prisma";
import { calculateSignalScore } from "@/lib/scoring/signals";
import { SignalScoreCard } from "@/components/analysis/SignalScoreCard";
import { TopIdeasList } from "@/components/analysis/TopIdeasList";
import { VerdictCard } from "@/components/analysis/VerdictCard";
import { ValidationPlan } from "@/components/analysis/ValidationPlan";
import { CopyReportLinkButton } from "@/components/report/CopyReportLinkButton";
import { SignalArtwork } from "@/components/brand/SignalArtwork";
import { DecisionFirstPanel } from "@/components/analysis/DecisionFirstPanel";
import type { DecisionResult, TopIdea, ValidationDay } from "@/hooks/useAnalysis";

type PageProps = {
  params: Promise<{ slug: string }>;
};

type SignalData = {
  package?: { weeklyDownloads?: number };
  github?: {
    stars?: number;
    hostingRequestsLast90d?: number;
    enterpriseRequestsLast90d?: number;
    lastCommitDays?: number;
    velocityTrend?: "accelerating" | "stable" | "declining";
    skipSignalsFound?: string[];
    isArchived?: boolean;
  };
  hn?: { unsolvedPosts?: number };
  competition?: { crowdednessScore?: number };
  signalScore?: ReturnType<typeof calculateSignalScore>;
};

async function getAnalysis(slug: string) {
  return prisma.analysis.findFirst({
    where: { slug, isPublic: true },
    include: { target: true },
  });
}

function asTopIdeas(value: unknown): TopIdea[] {
  return Array.isArray(value) ? (value as TopIdea[]) : [];
}

function asValidationPlan(value: unknown): ValidationDay[] {
  return Array.isArray(value) ? (value as ValidationDay[]) : [];
}

function signalScoreFromData(signalData: SignalData | null, analysis: NonNullable<Awaited<ReturnType<typeof getAnalysis>>>) {
  if (signalData?.signalScore) return signalData.signalScore;
  if (signalData) {
    return calculateSignalScore({
      weeklyDownloads: signalData.package?.weeklyDownloads,
      stars: signalData.github?.stars,
      hostingRequestsLast90d: signalData.github?.hostingRequestsLast90d,
      enterpriseRequestsLast90d: signalData.github?.enterpriseRequestsLast90d,
      unsolvedPosts: signalData.hn?.unsolvedPosts,
      crowdednessScore: signalData.competition?.crowdednessScore,
      lastCommitDays: signalData.github?.lastCommitDays,
      velocityTrend: signalData.github?.velocityTrend,
      skipSignalsFound: signalData.github?.skipSignalsFound,
      isArchived: signalData.github?.isArchived,
    });
  }

  return {
    total: ((analysis.demandScore ?? 0) + (analysis.crowdednessScore ?? 0)) / 2,
    breakdown: {
      tier1: analysis.demandScore ?? 0,
      tier2: analysis.crowdednessScore ?? 0,
      tier3: analysis.wtpScore ?? 0,
      tier4: analysis.moatScore ?? 0,
    },
  };
}

function decisionFromAnalysis(
  analysis: NonNullable<Awaited<ReturnType<typeof getAnalysis>>>,
  signalScoreTotal: number
): DecisionResult | null {
  if (!analysis.bestIdea || !analysis.verdict) return null;

  return {
    verdict: analysis.verdict,
    confidence: analysis.confidence ?? 0,
    reasoning: analysis.verdictReasoning ?? "Signal-backed verdict generated by StackSignal.",
    bestIdea: analysis.bestIdea as TopIdea,
    scores: {
      demand: analysis.demandScore ?? 0,
      founderFit: analysis.founderFitScore ?? 0,
      crowdedness: analysis.crowdednessScore ?? 0,
      wtp: analysis.wtpScore ?? 0,
      gtmFit: analysis.gtmFitScore ?? 0,
      buildComplexity: analysis.buildComplexity ?? 0,
      speedToRevenue: analysis.speedToRevenue ?? 0,
      moat: analysis.moatScore ?? 0,
      platformRisk: analysis.platformRisk ?? 0,
      composite: signalScoreTotal,
    },
    skipReasons: Array.isArray(analysis.skipReasons)
      ? (analysis.skipReasons as DecisionResult["skipReasons"])
      : [],
    validationPlan: asValidationPlan(analysis.validationPlan),
    mvpScope: {
      coreFeatures: [],
      excludedFeatures: [],
      firstCustomerPath: "",
    },
    founderAdvantage: null,
    founderWarning: null,
    signalScoreTotal,
    buildRoomId: analysis.buildRoomId,
    targetName: analysis.target?.displayName ?? analysis.rawInput,
  };
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const analysis = await getAnalysis(slug);
  if (!analysis) return { title: "Report not found" };

  const idea = analysis.bestIdea as { name?: string } | null;
  const verdict = analysis.verdict ?? "WATCH";

  return {
    title: `${verdict}: ${idea?.name || "Analysis"} — StackSignal`,
    description: analysis.verdictReasoning?.slice(0, 160) || "Signal-backed startup analysis",
    openGraph: {
      title: `${verdict} verdict: ${idea?.name || analysis.rawInput}`,
      description: analysis.verdictReasoning?.slice(0, 200) || "Signal-backed startup analysis",
    },
  };
}

export default async function ReportPage({ params }: PageProps) {
  const { slug } = await params;
  const analysis = await getAnalysis(slug);
  if (!analysis) notFound();

  const ideas = asTopIdeas(analysis.topIdeas);
  const signalData = analysis.target?.signalData as SignalData | null;
  const signalScore = signalScoreFromData(signalData, analysis);
  const decision = decisionFromAnalysis(analysis, signalScore.total);
  const reportUrl = `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/report/${slug}`;
  const shareText = `${decision?.verdict ?? "WATCH"} verdict on ${analysis.rawInput}\n\n${analysis.verdictReasoning?.slice(0, 100) ?? "Signal-backed analysis"}...\n\nFull analysis:`;

  return (
    <main className="relative mx-auto max-w-7xl px-4 py-10 sm:px-6">
      <section className="mb-10 grid gap-6 lg:grid-cols-[1.15fr_0.85fr]">
        <div className="ink-card p-6 sm:p-8">
          <div className="mb-6 flex flex-wrap items-center gap-2">
            <span className="kicker">StackSignal Report</span>
            <span className="text-xs text-[#1A1A1A]/25">·</span>
            <span className="font-mono text-xs text-[#1A1A1A]/40">
            {new Date(analysis.createdAt).toLocaleDateString("en-US", {
              month: "long",
              day: "numeric",
              year: "numeric",
            })}
            </span>
          </div>
          <h1 className="display-title text-6xl uppercase sm:text-8xl">
            {decision?.verdict ?? "WATCH"} signal.
            <span className="block text-action">{decision?.bestIdea.name ?? "Opportunity map"}</span>
          </h1>
          <div className="mt-6 font-mono text-xs uppercase tracking-[0.18em] text-[#1A1A1A]/40">{analysis.rawInput}</div>
        </div>
        <SignalArtwork label="Shareable signal artifact" compact />
      </section>

      <div className="grid gap-8 lg:grid-cols-[0.78fr_1.22fr]">
        <aside className="space-y-8">
          <SignalScoreCard score={signalScore} />
          <div className="border border-ink bg-ink p-5 text-canvas">
            <p className="font-heading text-3xl uppercase leading-none tracking-[-0.06em]">STACKSIGNAL 2026</p>
            <p className="mt-3 font-mono text-[10px] uppercase leading-5 tracking-[0.16em] text-canvas/55">
              A public artifact for founder decisions. Share the report, not the spreadsheet.
            </p>
          </div>
        </aside>

        <section className="min-w-0">
      {ideas.length > 0 ? (
        <div className="mb-8">
          <DecisionFirstPanel ideas={ideas} signalScore={signalScore} decision={decision} locked={!decision} slug={slug} />
        </div>
      ) : null}

      {decision ? (
        <div className="mb-8" id="verdict">
          <VerdictCard verdict={decision} />
        </div>
      ) : null}

      {ideas.length > 0 ? (
        <div className="mb-8">
          <h2 className="mb-4 font-heading text-2xl font-black tracking-tight">Other business paths</h2>
          <TopIdeasList ideas={ideas} tier={decision ? "paid" : "free"} />
        </div>
      ) : null}

      {decision?.validationPlan && decision.validationPlan.length > 0 ? (
        <div className="mb-8">
          <h2 className="mb-4 font-heading text-2xl font-black tracking-tight">7-day validation plan</h2>
          <ValidationPlan plan={decision.validationPlan} />
        </div>
      ) : null}

      <div className="mt-8 border-t border-[#1A1A1A]/15 pt-8">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="mb-3 text-sm font-bold">Share this report</p>
            <div className="flex gap-2">
              <a
                href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(reportUrl)}`}
                target="_blank"
                rel="noreferrer"
                className="border border-[#E8E4DD] px-3 py-2 text-xs font-bold hover:border-[#FF4800] hover:text-[#FF4800]"
              >
                Share on X →
              </a>
              <CopyReportLinkButton url={reportUrl} />
            </div>
          </div>

          <div className="text-right">
            <p className="mb-2 text-sm text-[#1A1A1A]/50">Get a verdict on your own idea</p>
            <Link href="/" className="bg-[#1A1A1A] px-4 py-2 text-xs font-bold uppercase tracking-wider text-white">
              Analyze your repo →
            </Link>
          </div>
        </div>
      </div>
        </section>
      </div>
    </main>
  );
}
