#!/usr/bin/env bash
# wreckit — CI config detection, scoring, and generation
# Usage: ./ci-integration.sh [project-path] [--generate]
# Output: JSON to stdout, human summary to stderr
# --generate: write starter GitHub Actions workflow if no CI found
# Exit 0 = results produced, check JSON verdict for pass/fail

set -euo pipefail
PROJECT="${1:-.}"
GENERATE=false
if [ "${2:-}" = "--generate" ]; then
  GENERATE=true
fi
cd "$PROJECT"

echo "=== CI Integration Check ===" >&2
echo "Project: $(pwd)" >&2

# ─── Detect CI configs ────────────────────────────────────────────────────────

CI_FOUND=false
CI_TYPE=""
CI_FILE=""

# GitHub Actions
if ls .github/workflows/*.yml >/dev/null 2>&1 || ls .github/workflows/*.yaml >/dev/null 2>&1; then
  CI_FOUND=true
  CI_TYPE="github-actions"
  CI_FILE=$(ls .github/workflows/*.yml .github/workflows/*.yaml 2>/dev/null | head -1 || true)
  echo "Found GitHub Actions: $CI_FILE" >&2
fi

# GitLab CI
if [ "$CI_FOUND" = false ] && [ -f ".gitlab-ci.yml" ]; then
  CI_FOUND=true
  CI_TYPE="gitlab-ci"
  CI_FILE=".gitlab-ci.yml"
  echo "Found GitLab CI: $CI_FILE" >&2
fi

# CircleCI
if [ "$CI_FOUND" = false ] && [ -f ".circleci/config.yml" ]; then
  CI_FOUND=true
  CI_TYPE="circleci"
  CI_FILE=".circleci/config.yml"
  echo "Found CircleCI: $CI_FILE" >&2
fi

# Jenkins
if [ "$CI_FOUND" = false ] && [ -f "Jenkinsfile" ]; then
  CI_FOUND=true
  CI_TYPE="jenkins"
  CI_FILE="Jenkinsfile"
  echo "Found Jenkinsfile" >&2
fi

# Azure Pipelines
if [ "$CI_FOUND" = false ] && [ -f "azure-pipelines.yml" ]; then
  CI_FOUND=true
  CI_TYPE="azure-pipelines"
  CI_FILE="azure-pipelines.yml"
  echo "Found Azure Pipelines: $CI_FILE" >&2
fi

# Travis CI
if [ "$CI_FOUND" = false ] && [ -f ".travis.yml" ]; then
  CI_FOUND=true
  CI_TYPE="travis"
  CI_FILE=".travis.yml"
  echo "Found Travis CI: $CI_FILE" >&2
fi

# ─── Score existing CI config ─────────────────────────────────────────────────

SCORE=0
MISSING_STEPS="[]"
GENERATED_CONFIG_PATH=""

if [ "$CI_FOUND" = true ] && [ -n "$CI_FILE" ] && [ -f "$CI_FILE" ]; then
  echo "Scoring $CI_FILE..." >&2
  missing=""

  # Tests present (40 pts)
  if grep -qiE "(npm test|npm run test|pytest|go test|cargo test|vitest|jest|mocha|yarn test)" "$CI_FILE" 2>/dev/null; then
    SCORE=$((SCORE + 40))
    echo "  ✓ Tests: +40pts" >&2
  else
    missing="${missing}\"tests\","
    echo "  ✗ Tests: 0pts" >&2
  fi

  # Type check present (30 pts)
  if grep -qiE "(tsc|mypy|pyright|flow|type-check|typecheck|--noEmit)" "$CI_FILE" 2>/dev/null; then
    SCORE=$((SCORE + 30))
    echo "  ✓ Type check: +30pts" >&2
  else
    missing="${missing}\"type-check\","
    echo "  ✗ Type check: 0pts" >&2
  fi

  # Coverage (20 pts)
  if grep -qiE "(coverage|--coverage|codecov|coveralls|lcov)" "$CI_FILE" 2>/dev/null; then
    SCORE=$((SCORE + 20))
    echo "  ✓ Coverage: +20pts" >&2
  else
    missing="${missing}\"coverage\","
    echo "  ✗ Coverage: 0pts" >&2
  fi

  # Security scan (10 pts)
  if grep -qiE "(npm audit|snyk|trivy|semgrep|bandit|safety|dependabot|codeql)" "$CI_FILE" 2>/dev/null; then
    SCORE=$((SCORE + 10))
    echo "  ✓ Security scan: +10pts" >&2
  else
    missing="${missing}\"security-scan\","
    echo "  ✗ Security scan: 0pts" >&2
  fi

  if [ -n "$missing" ]; then
    MISSING_STEPS="[${missing%,}]"
  fi

  echo "  Total score: $SCORE/100" >&2

fi

# ─── Generate CI config if not found ─────────────────────────────────────────

if [ "$CI_FOUND" = false ]; then
  echo "" >&2
  echo "No CI configuration found." >&2

  # Detect project type for config generation
  SETUP_STEP="- uses: actions/setup-node@v4\n        with: { node-version: '20' }"
  INSTALL_CMD="npm install"
  TYPECHECK_CMD="npx tsc --noEmit"
  TEST_CMD="npm test"

  if [ -f "go.mod" ]; then
    SETUP_STEP="- uses: actions/setup-go@v5\n        with: { go-version: '1.22' }"
    INSTALL_CMD="go mod download"
    TYPECHECK_CMD="go vet ./..."
    TEST_CMD="go test ./..."
  elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
    SETUP_STEP="- uses: actions/setup-python@v5\n        with: { python-version: '3.12' }"
    INSTALL_CMD="pip install -r requirements.txt"
    TYPECHECK_CMD="python -m mypy . || true"
    TEST_CMD="python -m pytest"
  fi

  GENERATED_CONFIG_PATH=".github/workflows/wreckit-audit.yml"

  if [ "$GENERATE" = true ]; then
    mkdir -p ".github/workflows"
    cat > "$GENERATED_CONFIG_PATH" <<YAMLEOF
# Generated by wreckit ci-integration.sh
name: wreckit audit
on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - ${SETUP_STEP}
      - run: ${INSTALL_CMD}
      - run: ${TYPECHECK_CMD}
      - run: ${TEST_CMD}
YAMLEOF
    echo "Generated: $GENERATED_CONFIG_PATH" >&2
  else
    echo "Run with --generate flag to create $GENERATED_CONFIG_PATH" >&2
    GENERATED_CONFIG_PATH=""
  fi
fi

# ─── Determine verdict ────────────────────────────────────────────────────────

VERDICT="FAIL"
SUMMARY=""

if [ "$CI_FOUND" = false ]; then
  VERDICT="FAIL"
  SUMMARY="FAIL: No CI configuration found in project."
elif [ "$SCORE" -ge 70 ]; then
  VERDICT="PASS"
  SUMMARY="PASS: CI found (${CI_TYPE}), score ${SCORE}/100."
elif [ "$SCORE" -ge 40 ]; then
  VERDICT="WARN"
  SUMMARY="WARN: CI found (${CI_TYPE}) but incomplete, score ${SCORE}/100."
else
  VERDICT="FAIL"
  SUMMARY="FAIL: CI found (${CI_TYPE}) but critically incomplete, score ${SCORE}/100."
fi

# ─── Output ───────────────────────────────────────────────────────────────────

echo "" >&2
echo "CI found: $CI_FOUND" >&2
echo "CI type: ${CI_TYPE:-none}" >&2
echo "Score: $SCORE/100" >&2
echo "Verdict: $VERDICT" >&2
echo "Summary: $SUMMARY" >&2

CI_FILE_JSON="null"
if [ -n "$CI_FILE" ]; then
  CI_FILE_JSON="\"$CI_FILE\""
fi

GENERATED_JSON="null"
if [ -n "$GENERATED_CONFIG_PATH" ]; then
  GENERATED_JSON="\"$GENERATED_CONFIG_PATH\""
fi

cat <<EOF
{
  "ci_found": $CI_FOUND,
  "ci_type": "${CI_TYPE:-none}",
  "ci_file": $CI_FILE_JSON,
  "score_100": $SCORE,
  "missing_steps": $MISSING_STEPS,
  "generated_config_path": $GENERATED_JSON,
  "verdict": "$VERDICT",
  "summary": "$SUMMARY"
}
EOF
